---
title: "levadasept"
author: "Daniel Shapiro"
date: "10/7/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
library(tidyverse)
library(readxl)
```

```{r putinread}
putindat <- read_xlsx("raw-data/putin.xlsx")
```

```{r putinplot}
putingg <- ggplot(putindat, aes(x = Date, y = Percent, color = Opinion)) + 
  geom_point() +
  geom_line() +
  expand_limits(y = c(0, 100)) +
  labs(title = "2020 Monthly Domestic Approval of President Putin",
       subtitle = "Data from Levada Center",
       caption = "Data can be found at: https://www.levada.ru/2020/10/01/odobrenie-institutov-vlasti-26/")

putingg

ggsave("putingg.png")
```

```{r mishustinread}
mishustindat <- read_xlsx("raw-data/mishustin.xlsx")
```


```{r}
mishustingg <- ggplot(mishustindat, aes(x = Date, y = Percent, color = Opinion)) + 
  geom_point() +
  geom_line() +
  expand_limits(y = c(0, 100)) +
  labs(title = "2020 Monthly Domestic Approval of Prime Minister Mishustin",
       subtitle = "Data from Levada Center",
       caption = "Data can be found at: https://www.levada.ru/2020/10/01/odobrenie-institutov-vlasti-26/")

mishustingg

ggsave("mishustin.png")
```